/**
 * Automatic setup for AI tools integration
 * Zero-configuration setup for Cursor, Claude, and any AI assistant
 */

import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

// ESM has no `__dirname`; derive it from the module URL.
const __dirname = path.dirname(fileURLToPath(import.meta.url));

interface SetupOptions {
  projectRoot?: string;
  aiProviders?: string[];
  skipConfirmation?: boolean;
  silent?: boolean;
}

export class ExoAutoSetup {
  private projectRoot: string;
  private options: SetupOptions;

  constructor(options: SetupOptions = {}) {
    this.projectRoot = options.projectRoot || process.cwd();
    this.options = options;
  }

  /**
   * Run complete auto-setup
   */
  async setup(): Promise<void> {
    if (!this.options.silent) {
      console.log('🚀 Setting up Exodra AI integration...\n');
    }

    try {
      // 1. Check if this is an Exodra project
      await this.validateExodraProject();

      // 2. Install introspect if needed
      await this.ensureIntrospectInstalled();

      // 3. Detect and configure AI providers
      await this.setupAIProviders();

      // 4. Create Cursor integration
      await this.setupCursorIntegration();

      // 5. Create project configuration
      await this.createProjectConfig();

      // 6. Copy LLM context file
      await this.copyLLMContext();

      // 7. Test integration
      await this.testIntegration();

      if (!this.options.silent) {
        this.printSuccessMessage();
      }
    } catch (error) {
      console.error('❌ Setup failed:', (error as Error).message);
      throw error;
    }
  }

  private async validateExodraProject(): Promise<void> {
    const packageJsonPath = path.join(this.projectRoot, 'package.json');
    
    try {
      const packageJson = JSON.parse(
        await fs.readFile(packageJsonPath, 'utf-8')
      );

      const hasExodra = 
        packageJson.dependencies?.['@exodra/core'] ||
        packageJson.devDependencies?.['@exodra/core'] ||
        packageJson.dependencies?.['@exodra/jsx'] ||
        packageJson.devDependencies?.['@exodra/jsx'];

      if (!hasExodra) {
        throw new Error(
          'This does not appear to be an Exodra project. Install @exodra/core first.'
        );
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        throw new Error('No package.json found. Is this a valid project directory?', {
          cause: error,
        });
      }
      throw error;
    }
  }

  private async ensureIntrospectInstalled(): Promise<void> {
    const packageJsonPath = path.join(this.projectRoot, 'package.json');
    const packageJson = JSON.parse(
      await fs.readFile(packageJsonPath, 'utf-8')
    );

    const hasIntrospect = 
      packageJson.dependencies?.['@exodra/introspect'] ||
      packageJson.devDependencies?.['@exodra/introspect'];

    if (!hasIntrospect) {
      if (!this.options.silent) {
        console.log('📦 Installing @exodra/introspect...');
      }

      try {
        execSync('npm install @exodra/introspect --save-dev', {
          cwd: this.projectRoot,
          stdio: this.options.silent ? 'ignore' : 'inherit'
        });
      } catch (error) {
        throw new Error('Failed to install @exodra/introspect. Please install manually.', {
          cause: error,
        });
      }
    }
  }

  private async setupAIProviders(): Promise<void> {
    const providers = [];

    // Auto-detect available API keys
    if (process.env.OPENAI_API_KEY) {
      providers.push('openai');
    }

    if (process.env.ANTHROPIC_API_KEY) {
      providers.push('anthropic');
    }

    // Check for GitHub Copilot
    try {
      execSync('code --version', { stdio: 'ignore' });
      const extensions = execSync('code --list-extensions', { 
        encoding: 'utf-8',
        stdio: 'pipe'
      });
      
      if (extensions.includes('GitHub.copilot')) {
        providers.push('github-copilot');
      }
    } catch {
      // VS Code or Copilot not available
    }

    if (providers.length === 0) {
      console.log('⚠️  No AI providers detected. You can configure them later.');
      return;
    }

    if (!this.options.silent) {
      console.log(`🤖 Detected AI providers: ${providers.join(', ')}`);
    }
  }

  private async setupCursorIntegration(): Promise<void> {
    const cursorToolsPath = path.join(this.projectRoot, '.cursor-tools.js');

    // Check if already exists
    try {
      await fs.access(cursorToolsPath);
      if (!this.options.skipConfirmation && !this.options.silent) {
        console.log('📝 .cursor-tools.js already exists, skipping...');
      }
      return;
    } catch {
      // File doesn't exist, create it
    }

    const cursorToolsContent = `/**
 * Exodra AI Integration for Cursor/Claude
 * Auto-generated by @exodra/introspect
 */

import { setupCursorIntegration } from '@exodra/introspect/integrations/cursor';

// Auto-setup with project detection
const integration = await setupCursorIntegration({
  autoDetectPlugins: true,
  autoDetectAIProviders: true,
  enableRealtimeAnalysis: true
});

export const tools = [
  integration.tool
];

// Export for other AI tools
export const exodraContext = integration.context;
export const analysisCapabilities = integration.capabilities;

console.log('✅ Exodra AI integration loaded');
console.log('📊 Available capabilities:', integration.capabilities.join(', '));
`;

    await fs.writeFile(cursorToolsPath, cursorToolsContent);

    if (!this.options.silent) {
      console.log('✅ Created .cursor-tools.js for AI integration');
    }
  }

  private async createProjectConfig(): Promise<void> {
    const configPath = path.join(this.projectRoot, 'exo.config.js');

    // Check if config already exists
    try {
      await fs.access(configPath);
      return; // Don't overwrite existing config
    } catch {
      // File doesn't exist, create it
    }

    const configContent = `/**
 * Exodra Configuration
 * Auto-generated with AI integration setup
 */

export default {
  // Core Exodra settings
  core: {
    strict: true,
    validateSchemas: true
  },

  // AI-powered introspection
  introspect: {
    enabled: true,
    
    // Auto-detect and configure AI providers
    ai: {
      autoDetect: true,
      providers: [
        // OpenAI (if API key available)
        process.env.OPENAI_API_KEY && {
          name: 'openai',
          type: 'openai',
          config: {
            apiKey: process.env.OPENAI_API_KEY,
            model: 'gpt-4'
          }
        },
        
        // Anthropic (if API key available)  
        process.env.ANTHROPIC_API_KEY && {
          name: 'anthropic',
          type: 'anthropic',
          config: {
            apiKey: process.env.ANTHROPIC_API_KEY
          }
        }
      ].filter(Boolean),
      
      // Automatic fallbacks
      fallback: ['openai', 'anthropic'],
      
      // Context optimization
      context: {
        includePluginAnalysis: true,
        includePerformanceMetrics: true,
        maxContextSize: '100KB'
      }
    },

    // Plugin system
    plugins: {
      autoDiscovery: true,
      
      // Built-in plugins
      enabled: [
        'router-analysis',
        'component-analysis', 
        'performance-analysis',
        'security-analysis'
      ]
    },

    // Analysis preferences
    analysis: {
      typescript: {
        strict: true,
        skipLibCheck: false
      },
      
      performance: {
        bundleAnalysis: true,
        renderTracking: true,
        memoryLeakDetection: true
      },
      
      security: {
        routeGuardAnalysis: true,
        inputValidation: true,
        xssProtection: true
      }
    }
  },

  // Development tools
  devTools: {
    enabled: process.env.NODE_ENV === 'development',
    
    chromeExtension: {
      enabled: true,
      port: 9222
    }
  }
};
`;

    await fs.writeFile(configPath, configContent);

    if (!this.options.silent) {
      console.log('✅ Created exo.config.js with AI integration');
    }
  }

  private async copyLLMContext(): Promise<void> {
    const contextPath = path.join(this.projectRoot, 'EXODRA_LLM_CONTEXT.md');

    // Check if already exists
    try {
      await fs.access(contextPath);
      return; // Don't overwrite
    } catch {
      // Copy from package
    }

    // dist/auto-setup.js → package root is one level up; the file is shipped
    // there (see the package's `files` field).
    const sourceContextPath = path.join(
      __dirname,
      '..',
      'EXODRA_LLM_CONTEXT.md'
    );
    
    try {
      const contextContent = await fs.readFile(sourceContextPath, 'utf-8');
      await fs.writeFile(contextPath, contextContent);

      if (!this.options.silent) {
        console.log('✅ Copied LLM context file for AI understanding');
      }
    } catch (error) {
      // If source file not found, create a basic one
      const basicContext = `# Exodra Project Context

This is an Exodra framework project with AI integration enabled.

## Available Tools
- @exodra/introspect for code analysis
- Cursor/Claude integration via .cursor-tools.js
- Auto-configured AI providers

## Usage
AI assistants can automatically analyze and help with this Exodra project.
`;

      await fs.writeFile(contextPath, basicContext);
    }
  }

  private async testIntegration(): Promise<void> {
    if (!this.options.silent) {
      console.log('🧪 Testing AI integration...');
    }

    try {
      // Test introspect CLI
      execSync('npx exo-introspect --version', {
        cwd: this.projectRoot,
        stdio: 'ignore'
      });

      // Test basic analysis
      execSync('npx exo-introspect analyze --dry-run', {
        cwd: this.projectRoot,
        stdio: 'ignore'
      });

      if (!this.options.silent) {
        console.log('✅ Integration test passed');
      }
    } catch (error) {
      console.warn('⚠️  Integration test failed, but setup should still work');
    }
  }

  private printSuccessMessage(): void {
    console.log(`
🎉 Exodra AI Integration Setup Complete!

📁 Files created:
  ✅ .cursor-tools.js        - Cursor/Claude integration
  ✅ exo.config.js          - Exodra configuration  
  ✅ EXODRA_LLM_CONTEXT.md  - AI context file

🤖 AI Tools Ready:
  • Cursor with Claude integration
  • Any AI tool can read EXODRA_LLM_CONTEXT.md
  • Auto-detected AI providers configured

🚀 Next Steps:
  1. Open project in Cursor
  2. Ask Claude: "Analyze my Exodra app"
  3. Start AI-powered development!

📖 Learn more: https://exodra-framework.github.io/exodra/

💡 Tip: Run 'exo-introspect analyze --ai' for immediate insights
`);
  }
}

/**
 * CLI command for auto-setup
 */
export async function autoSetup(options: SetupOptions = {}): Promise<void> {
  const setup = new ExoAutoSetup(options);
  await setup.setup();
}

/**
 * Setup with prompts for interactive use
 */
export async function interactiveSetup(): Promise<void> {
  console.log('🚀 Exodra AI Integration Setup\n');

  // In a real implementation, we'd use inquirer or similar for prompts
  const options: SetupOptions = {
    skipConfirmation: false,
    silent: false
  };

  const setup = new ExoAutoSetup(options);
  await setup.setup();
}

// Export for CLI usage
if (import.meta.url === `file://${process.argv[1]}`) {
  autoSetup({ silent: false }).catch(console.error);
}