import type { TExoSchema } from '../types/TExoSchema';
import type { TExoSchemaProps } from '../types/TExoSchemaProps';

/**
 * Creates an Exodra schema node for elements or components.
 * 
 * @param type - HTML element tag name (e.g. 'div'), '#text' for text nodes, or component function
 * @param attrs - Three-props attributes object with static, bindables, bindableLists, and handlers
 * @param cacheKey - Optional symbol for clone-caching in loops (auto-generated by babel plugin)
 * @returns Schema object for the Exodra renderer
 * 
 * @example
 * ```typescript
 * // HTML element with three-props architecture
 * h('div', {
 *   static: { id: 'container', class: 'box', children: text('Hello') },
 *   bindables: { hidden: () => isHidden.value },
 *   handlers: { onClick: handleClick }
 * })
 * 
 * // Component with props
 * h(MyComponent, {
 *   static: { title: 'Hello', count: 42 }
 * })
 * 
 * // Fragment for mixed children
 * h('#fragment', {
 *   bindableLists: { children: dynamicList }
 * })
 * ```
 */
export function h(
    type: TExoSchema['type'],
    attrs: TExoSchemaProps = {},
    cacheKey?: symbol | string
): TExoSchema {
    return (
        cacheKey === undefined ? { type, attrs } : { type, attrs, cacheKey }
    ) as TExoSchema;
}
